// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

package main

import "github.com/valyala/fasthttp"

// Package github.com/valyala/fasthttp@v1.23.0
func Redirect_GithubComValyalaFasthttpV1230() {
	// Redirect via method calls.
	{
		// Redirect via method calls on github.com/valyala/fasthttp.RequestCtx.
		{
			// func (*RequestCtx).Redirect(uri string, statusCode int)
			{
				urlString960 := source().(string)
				var rece fasthttp.RequestCtx
				rece.Redirect(urlString960, 0) // $redirectUrl=urlString960
			}
			// func (*RequestCtx).RedirectBytes(uri []byte, statusCode int)
			{
				urlByte289 := source().([]byte)
				var rece fasthttp.RequestCtx
				rece.RedirectBytes(urlByte289, 0) // $redirectUrl=urlByte289
			}
		}
	}
}
