// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

package main

import (
	"io"

	"github.com/valyala/fasthttp"
)

// Package github.com/valyala/fasthttp@v1.23.0
func ResponseBody_GithubComValyalaFasthttpV1230() {
	// Response body is set via a method call (the content-type is implicit in the method name).
	{
		// Response body is set via a method call on the github.com/valyala/fasthttp.RequestCtx type (the content-type is implicit in the method name).
		{
			// func (*RequestCtx).Error(msg string, statusCode int)
			{
				bodyString262 := source().(string)
				var rece fasthttp.RequestCtx
				rece.Error(bodyString262, 0) // $contentType=text/plain $responseBody=bodyString262
			}
		}
	}
	// Response body and content-type are both set via a single call of a method.
	{
		// Response body and content-type are both set via a single call of a method on the github.com/valyala/fasthttp.RequestCtx type.
		{
			// func (*RequestCtx).Success(contentType string, body []byte)
			{
				bodyByte454 := source().([]byte)
				var rece fasthttp.RequestCtx
				rece.Success("application/json", bodyByte454) // $contentType=application/json $responseBody=bodyByte454
			}
			// func (*RequestCtx).SuccessString(contentType string, body string)
			{
				bodyString667 := source().(string)
				var rece fasthttp.RequestCtx
				rece.SuccessString("application/json", bodyString667) // $contentType=application/json $responseBody=bodyString667
			}
		}
	}
	// Response body is set via a call of a type method.
	{
		// Response body is set via a call of a method on the github.com/valyala/fasthttp.Request type.
		{
			// func (*Request).AppendBody(p []byte)
			{
				bodyByte307 := source().([]byte)
				var rece fasthttp.Request
				rece.AppendBody(bodyByte307) // $responseBody=bodyByte307
			}
			// func (*Request).AppendBodyString(s string)
			{
				bodyString938 := source().(string)
				var rece fasthttp.Request
				rece.AppendBodyString(bodyString938) // $responseBody=bodyString938
			}
		}
		// Response body is set via a call of a method on the github.com/valyala/fasthttp.RequestCtx type.
		{
			// func (*RequestCtx).SetBody(body []byte)
			{
				bodyByte600 := source().([]byte)
				var rece fasthttp.RequestCtx
				rece.SetBody(bodyByte600) // $responseBody=bodyByte600
			}
			// func (*RequestCtx).SetBodyStream(bodyStream io.Reader, bodySize int)
			{
				bodyReader222 := source().(io.Reader)
				var rece fasthttp.RequestCtx
				rece.SetBodyStream(bodyReader222, 0) // $responseBody=bodyReader222
			}
			// func (*RequestCtx).SetBodyStreamWriter(sw StreamWriter)
			{
				bodyStreamWriter343 := source().(fasthttp.StreamWriter)
				var rece fasthttp.RequestCtx
				rece.SetBodyStreamWriter(bodyStreamWriter343) // $responseBody=bodyStreamWriter343
			}
			// func (*RequestCtx).SetBodyString(body string)
			{
				bodyString481 := source().(string)
				var rece fasthttp.RequestCtx
				rece.SetBodyString(bodyString481) // $responseBody=bodyString481
			}
			// func (*RequestCtx).Write(p []byte) (int, error)
			{
				bodyByte184 := source().([]byte)
				var rece fasthttp.RequestCtx
				rece.Write(bodyByte184) // $responseBody=bodyByte184
			}
			// func (*RequestCtx).WriteString(s string) (int, error)
			{
				bodyString985 := source().(string)
				var rece fasthttp.RequestCtx
				rece.WriteString(bodyString985) // $responseBody=bodyString985
			}
		}
		// Response body is set via a call of a method on the github.com/valyala/fasthttp.Response type.
		{
			// func (*Response).AppendBody(p []byte)
			{
				bodyByte970 := source().([]byte)
				var rece fasthttp.Response
				rece.AppendBody(bodyByte970) // $responseBody=bodyByte970
			}
			// func (*Response).AppendBodyString(s string)
			{
				bodyString638 := source().(string)
				var rece fasthttp.Response
				rece.AppendBodyString(bodyString638) // $responseBody=bodyString638
			}
		}
	}
}
