// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

package main

import (
	"io"

	"github.com/valyala/fasthttp"
)

// Package github.com/valyala/fasthttp@v1.23.0
func UntrustedFlowSources_GithubComValyalaFasthttpV1230() {
	// Untrusted flow sources from method calls.
	{
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.Args.
		{
			// func (*Args).Peek(key string) []byte
			{
				var receiverArgs896 fasthttp.Args
				resultIntoByte182854 := receiverArgs896.Peek("")
				sink(resultIntoByte182854) // $untrustedFlowSource
			}
			// func (*Args).PeekBytes(key []byte) []byte
			{
				var receiverArgs223 fasthttp.Args
				resultIntoByte665257 := receiverArgs223.PeekBytes(nil)
				sink(resultIntoByte665257) // $untrustedFlowSource
			}
			// func (*Args).PeekMulti(key string) [][]byte
			{
				var receiverArgs236 fasthttp.Args
				resultIntoByte299147 := receiverArgs236.PeekMulti("")
				sink(resultIntoByte299147) // $untrustedFlowSource
			}
			// func (*Args).PeekMultiBytes(key []byte) [][]byte
			{
				var receiverArgs530 fasthttp.Args
				resultIntoByte862191 := receiverArgs530.PeekMultiBytes(nil)
				sink(resultIntoByte862191) // $untrustedFlowSource
			}
			// func (*Args).QueryString() []byte
			{
				var receiverArgs115 fasthttp.Args
				resultIntoByte835233 := receiverArgs115.QueryString()
				sink(resultIntoByte835233) // $untrustedFlowSource
			}
			// func (*Args).String() string
			{
				var receiverArgs714 fasthttp.Args
				resultIntoString625463 := receiverArgs714.String()
				sink(resultIntoString625463) // $untrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.Cookie.
		{
			// func (*Cookie).Cookie() []byte
			{
				var receiverCookie704 fasthttp.Cookie
				resultIntoByte726859 := receiverCookie704.Cookie()
				sink(resultIntoByte726859) // $untrustedFlowSource
			}
			// func (*Cookie).Domain() []byte
			{
				var receiverCookie194 fasthttp.Cookie
				resultIntoByte505442 := receiverCookie194.Domain()
				sink(resultIntoByte505442) // $untrustedFlowSource
			}
			// func (*Cookie).Key() []byte
			{
				var receiverCookie406 fasthttp.Cookie
				resultIntoByte833554 := receiverCookie406.Key()
				sink(resultIntoByte833554) // $untrustedFlowSource
			}
			// func (*Cookie).Path() []byte
			{
				var receiverCookie315 fasthttp.Cookie
				resultIntoByte825914 := receiverCookie315.Path()
				sink(resultIntoByte825914) // $untrustedFlowSource
			}
			// func (*Cookie).String() string
			{
				var receiverCookie930 fasthttp.Cookie
				resultIntoString723432 := receiverCookie930.String()
				sink(resultIntoString723432) // $untrustedFlowSource
			}
			// func (*Cookie).Value() []byte
			{
				var receiverCookie501 fasthttp.Cookie
				resultIntoByte398628 := receiverCookie501.Value()
				sink(resultIntoByte398628) // $untrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.Request.
		{
			// func (*Request).Body() []byte
			{
				var receiverRequest728 fasthttp.Request
				resultIntoByte360428 := receiverRequest728.Body()
				sink(resultIntoByte360428) // $untrustedFlowSource
			}
			// func (*Request).BodyGunzip() ([]byte, error)
			{
				var receiverRequest374 fasthttp.Request
				resultIntoByte571727, _ := receiverRequest374.BodyGunzip()
				sink(resultIntoByte571727) // $untrustedFlowSource
			}
			// func (*Request).BodyInflate() ([]byte, error)
			{
				var receiverRequest214 fasthttp.Request
				resultIntoByte119906, _ := receiverRequest214.BodyInflate()
				sink(resultIntoByte119906) // $untrustedFlowSource
			}
			// func (*Request).BodyUnbrotli() ([]byte, error)
			{
				var receiverRequest445 fasthttp.Request
				resultIntoByte395159, _ := receiverRequest445.BodyUnbrotli()
				sink(resultIntoByte395159) // $untrustedFlowSource
			}
			// func (*Request).BodyWriteTo(w io.Writer) error
			{
				var receiverRequest623 fasthttp.Request
				var paramIntoWriter756923 io.Writer
				receiverRequest623.BodyWriteTo(paramIntoWriter756923)
				sink(paramIntoWriter756923) // $untrustedFlowSource
			}
			// func (*Request).Host() []byte
			{
				var receiverRequest691 fasthttp.Request
				resultIntoByte812692 := receiverRequest691.Host()
				sink(resultIntoByte812692) // $untrustedFlowSource
			}
			// func (*Request).MultipartForm() (*mime/multipart.Form, error)
			{
				var receiverRequest863 fasthttp.Request
				resultIntoForm455791, _ := receiverRequest863.MultipartForm()
				sink(resultIntoForm455791) // $untrustedFlowSource
			}
			// func (*Request).PostArgs() *Args
			{
				var receiverRequest233 fasthttp.Request
				resultIntoArgs676794 := receiverRequest233.PostArgs()
				sink(resultIntoArgs676794) // $untrustedFlowSource
			}
			// func (*Request).RequestURI() []byte
			{
				var receiverRequest948 fasthttp.Request
				resultIntoByte382343 := receiverRequest948.RequestURI()
				sink(resultIntoByte382343) // $untrustedFlowSource
			}
			// func (*Request).String() string
			{
				var receiverRequest461 fasthttp.Request
				resultIntoString511407 := receiverRequest461.String()
				sink(resultIntoString511407) // $untrustedFlowSource
			}
			// func (*Request).URI() *URI
			{
				var receiverRequest238 fasthttp.Request
				resultIntoURI300342 := receiverRequest238.URI()
				sink(resultIntoURI300342) // $untrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.RequestCtx.
		{
			// func (*RequestCtx).FormFile(key string) (*mime/multipart.FileHeader, error)
			{
				var receiverRequestCtx277 fasthttp.RequestCtx
				resultIntoFileHeader481607, _ := receiverRequestCtx277.FormFile("")
				sink(resultIntoFileHeader481607) // $untrustedFlowSource
			}
			// func (*RequestCtx).FormValue(key string) []byte
			{
				var receiverRequestCtx314 fasthttp.RequestCtx
				resultIntoByte983664 := receiverRequestCtx314.FormValue("")
				sink(resultIntoByte983664) // $untrustedFlowSource
			}
			// func (*RequestCtx).Host() []byte
			{
				var receiverRequestCtx629 fasthttp.RequestCtx
				resultIntoByte654319 := receiverRequestCtx629.Host()
				sink(resultIntoByte654319) // $untrustedFlowSource
			}
			// func (*RequestCtx).Method() []byte
			{
				var receiverRequestCtx215 fasthttp.RequestCtx
				resultIntoByte990859 := receiverRequestCtx215.Method()
				sink(resultIntoByte990859) // $untrustedFlowSource
			}
			// func (*RequestCtx).MultipartForm() (*mime/multipart.Form, error)
			{
				var receiverRequestCtx868 fasthttp.RequestCtx
				resultIntoForm214670, _ := receiverRequestCtx868.MultipartForm()
				sink(resultIntoForm214670) // $untrustedFlowSource
			}
			// func (*RequestCtx).Path() []byte
			{
				var receiverRequestCtx376 fasthttp.RequestCtx
				resultIntoByte309585 := receiverRequestCtx376.Path()
				sink(resultIntoByte309585) // $untrustedFlowSource
			}
			// func (*RequestCtx).PostArgs() *Args
			{
				var receiverRequestCtx998 fasthttp.RequestCtx
				resultIntoArgs554595 := receiverRequestCtx998.PostArgs()
				sink(resultIntoArgs554595) // $untrustedFlowSource
			}
			// func (*RequestCtx).PostBody() []byte
			{
				var receiverRequestCtx417 fasthttp.RequestCtx
				resultIntoByte975743 := receiverRequestCtx417.PostBody()
				sink(resultIntoByte975743) // $untrustedFlowSource
			}
			// func (*RequestCtx).QueryArgs() *Args
			{
				var receiverRequestCtx123 fasthttp.RequestCtx
				resultIntoArgs716132 := receiverRequestCtx123.QueryArgs()
				sink(resultIntoArgs716132) // $untrustedFlowSource
			}
			// func (*RequestCtx).Referer() []byte
			{
				var receiverRequestCtx373 fasthttp.RequestCtx
				resultIntoByte139842 := receiverRequestCtx373.Referer()
				sink(resultIntoByte139842) // $untrustedFlowSource
			}
			// func (*RequestCtx).RequestURI() []byte
			{
				var receiverRequestCtx265 fasthttp.RequestCtx
				resultIntoByte208490 := receiverRequestCtx265.RequestURI()
				sink(resultIntoByte208490) // $untrustedFlowSource
			}
			// func (*RequestCtx).String() string
			{
				var receiverRequestCtx321 fasthttp.RequestCtx
				resultIntoString459730 := receiverRequestCtx321.String()
				sink(resultIntoString459730) // $untrustedFlowSource
			}
			// func (*RequestCtx).UserAgent() []byte
			{
				var receiverRequestCtx806 fasthttp.RequestCtx
				resultIntoByte510898 := receiverRequestCtx806.UserAgent()
				sink(resultIntoByte510898) // $untrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.RequestHeader.
		{
			// func (*RequestHeader).ContentType() []byte
			{
				var receiverRequestHeader211 fasthttp.RequestHeader
				resultIntoByte806953 := receiverRequestHeader211.ContentType()
				sink(resultIntoByte806953) // $untrustedFlowSource
			}
			// func (*RequestHeader).Header() []byte
			{
				var receiverRequestHeader582 fasthttp.RequestHeader
				resultIntoByte345543 := receiverRequestHeader582.Header()
				sink(resultIntoByte345543) // $untrustedFlowSource
			}
			// func (*RequestHeader).Host() []byte
			{
				var receiverRequestHeader765 fasthttp.RequestHeader
				resultIntoByte438124 := receiverRequestHeader765.Host()
				sink(resultIntoByte438124) // $untrustedFlowSource
			}
			// func (*RequestHeader).Method() []byte
			{
				var receiverRequestHeader207 fasthttp.RequestHeader
				resultIntoByte721180 := receiverRequestHeader207.Method()
				sink(resultIntoByte721180) // $untrustedFlowSource
			}
			// func (*RequestHeader).MultipartFormBoundary() []byte
			{
				var receiverRequestHeader978 fasthttp.RequestHeader
				resultIntoByte458497 := receiverRequestHeader978.MultipartFormBoundary()
				sink(resultIntoByte458497) // $untrustedFlowSource
			}
			// func (*RequestHeader).Peek(key string) []byte
			{
				var receiverRequestHeader179 fasthttp.RequestHeader
				resultIntoByte638455 := receiverRequestHeader179.Peek("")
				sink(resultIntoByte638455) // $untrustedFlowSource
			}
			// func (*RequestHeader).PeekBytes(key []byte) []byte
			{
				var receiverRequestHeader160 fasthttp.RequestHeader
				resultIntoByte491126 := receiverRequestHeader160.PeekBytes(nil)
				sink(resultIntoByte491126) // $untrustedFlowSource
			}
			// func (*RequestHeader).RawHeaders() []byte
			{
				var receiverRequestHeader123 fasthttp.RequestHeader
				resultIntoByte501435 := receiverRequestHeader123.RawHeaders()
				sink(resultIntoByte501435) // $untrustedFlowSource
			}
			// func (*RequestHeader).Referer() []byte
			{
				var receiverRequestHeader171 fasthttp.RequestHeader
				resultIntoByte585358 := receiverRequestHeader171.Referer()
				sink(resultIntoByte585358) // $untrustedFlowSource
			}
			// func (*RequestHeader).RequestURI() []byte
			{
				var receiverRequestHeader982 fasthttp.RequestHeader
				resultIntoByte419598 := receiverRequestHeader982.RequestURI()
				sink(resultIntoByte419598) // $untrustedFlowSource
			}
			// func (*RequestHeader).String() string
			{
				var receiverRequestHeader736 fasthttp.RequestHeader
				resultIntoString297429 := receiverRequestHeader736.String()
				sink(resultIntoString297429) // $untrustedFlowSource
			}
			// func (*RequestHeader).UserAgent() []byte
			{
				var receiverRequestHeader410 fasthttp.RequestHeader
				resultIntoByte354596 := receiverRequestHeader410.UserAgent()
				sink(resultIntoByte354596) // $untrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.ResponseHeader.
		{
			// func (*ResponseHeader).ContentType() []byte
			{
				var receiverResponseHeader228 fasthttp.ResponseHeader
				resultIntoByte398850 := receiverResponseHeader228.ContentType()
				sink(resultIntoByte398850) // $untrustedFlowSource
			}
			// func (*ResponseHeader).Header() []byte
			{
				var receiverResponseHeader627 fasthttp.ResponseHeader
				resultIntoByte268163 := receiverResponseHeader627.Header()
				sink(resultIntoByte268163) // $untrustedFlowSource
			}
			// func (*ResponseHeader).Server() []byte
			{
				var receiverResponseHeader601 fasthttp.ResponseHeader
				resultIntoByte547991 := receiverResponseHeader601.Server()
				sink(resultIntoByte547991) // $untrustedFlowSource
			}
			// func (*ResponseHeader).String() string
			{
				var receiverResponseHeader977 fasthttp.ResponseHeader
				resultIntoString586751 := receiverResponseHeader977.String()
				sink(resultIntoString586751) // $untrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on github.com/valyala/fasthttp.URI.
		{
			// func (*URI).FullURI() []byte
			{
				var receiverURI693 fasthttp.URI
				resultIntoByte867144 := receiverURI693.FullURI()
				sink(resultIntoByte867144) // $untrustedFlowSource
			}
			// func (*URI).Hash() []byte
			{
				var receiverURI491 fasthttp.URI
				resultIntoByte378448 := receiverURI491.Hash()
				sink(resultIntoByte378448) // $untrustedFlowSource
			}
			// func (*URI).Host() []byte
			{
				var receiverURI247 fasthttp.URI
				resultIntoByte803507 := receiverURI247.Host()
				sink(resultIntoByte803507) // $untrustedFlowSource
			}
			// func (*URI).LastPathSegment() []byte
			{
				var receiverURI522 fasthttp.URI
				resultIntoByte329259 := receiverURI522.LastPathSegment()
				sink(resultIntoByte329259) // $untrustedFlowSource
			}
			// func (*URI).Password() []byte
			{
				var receiverURI823 fasthttp.URI
				resultIntoByte525155 := receiverURI823.Password()
				sink(resultIntoByte525155) // $untrustedFlowSource
			}
			// func (*URI).Path() []byte
			{
				var receiverURI912 fasthttp.URI
				resultIntoByte931537 := receiverURI912.Path()
				sink(resultIntoByte931537) // $untrustedFlowSource
			}
			// func (*URI).PathOriginal() []byte
			{
				var receiverURI834 fasthttp.URI
				resultIntoByte499144 := receiverURI834.PathOriginal()
				sink(resultIntoByte499144) // $untrustedFlowSource
			}
			// func (*URI).QueryArgs() *Args
			{
				var receiverURI264 fasthttp.URI
				resultIntoArgs359439 := receiverURI264.QueryArgs()
				sink(resultIntoArgs359439) // $untrustedFlowSource
			}
			// func (*URI).QueryString() []byte
			{
				var receiverURI228 fasthttp.URI
				resultIntoByte522183 := receiverURI228.QueryString()
				sink(resultIntoByte522183) // $untrustedFlowSource
			}
			// func (*URI).RequestURI() []byte
			{
				var receiverURI205 fasthttp.URI
				resultIntoByte592858 := receiverURI205.RequestURI()
				sink(resultIntoByte592858) // $untrustedFlowSource
			}
			// func (*URI).Scheme() []byte
			{
				var receiverURI662 fasthttp.URI
				resultIntoByte276969 := receiverURI662.Scheme()
				sink(resultIntoByte276969) // $untrustedFlowSource
			}
			// func (*URI).String() string
			{
				var receiverURI246 fasthttp.URI
				resultIntoString814256 := receiverURI246.String()
				sink(resultIntoString814256) // $untrustedFlowSource
			}
			// func (*URI).Username() []byte
			{
				var receiverURI963 fasthttp.URI
				resultIntoByte921815 := receiverURI963.Username()
				sink(resultIntoByte921815) // $untrustedFlowSource
			}
		}
	}
	// Untrusted flow sources from struct fields.
	{
		// Untrusted flow sources from github.com/valyala/fasthttp.Request struct fields.
		{
			structRequest957 := new(fasthttp.Request)
			sink(structRequest957.Header) // $untrustedFlowSource
		}
		// Untrusted flow sources from github.com/valyala/fasthttp.RequestCtx struct fields.
		{
			structRequestCtx515 := new(fasthttp.RequestCtx)
			sink(structRequestCtx515.Request) // $untrustedFlowSource
		}
	}
	// Untrusted flow sources from types.
	{
		{
			var typeArgs759 fasthttp.Args
			sink(typeArgs759) // $untrustedFlowSource
		}
		{
			var typeCookie343 fasthttp.Cookie
			sink(typeCookie343) // $untrustedFlowSource
		}
	}
}
